apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-test-nginx
  name: argocd-test-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-test-nginx
  template:
    metadata:
      labels:
        app: argocd-test-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
